services:
  postgres:
    image: postgres:15
    container_name: hybrid-db
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  go-api:
    build:
      context: ./backend-go
      dockerfile: Dockerfile
    container_name: go-api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
      - python-compute
      - julia-compute
    restart: unless-stopped

  python-compute:
    build:
      context: ./backend-python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: unless-stopped

  julia-compute:
    build:
      context: ./backend-julia
      dockerfile: Dockerfile
    container_name: julia-compute
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
    restart: unless-stopped

  react-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
    - ./frontend/src:/app/src
    - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    stdin_open: true
    tty: true
    depends_on:
      - go-api
    restart: unless-stopped

volumes:
  postgres_data: {}