---
services:
  - type: web
    name: frontend
    runtime: docker
    env: production
    plan: free
    region: oregon
    dockerfilePath: frontend/Dockerfile
    environmentUrl: https://backend-go.onrender.com/api
  - type: web
    name: backend-go
    runtime: docker
    env: production
    plan: free
    region: oregon
    dockerfilePath: backend-go/Dockerfile
    envVars:
      - key: PYTHON_SERVICE_URL
        value: https://backend-python.onrender.com
      - key: JULIA_SERVICE_URL
        value: https://backend-julia.onrender.com
      - key: DATABASE_URL
        value: postgresql://user:pass@database:5432/mydb
  - type: web
    name: backend-python
    runtime: docker
    env: production
    plan: free
    region: oregon
    dockerfilePath: backend-python/Dockerfile
  - type: web
    name: backend-julia
    runtime: docker
    env: production
    plan: free
    region: oregon
    dockerfilePath: backend-julia/Dockerfile
  - type: database
    name: database
    plan: free
    region: oregon
    provider: postgres
